services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build: .
    container_name: covid_mspr
    depends_on:
      - db
    # Parfois, il ne semble pas récupérer les variables d'environnement du .env
    # On les redéfinit ici pour être sûr qu'elles soient bien prises en compte.
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    container_name: grafana
    ports:
      - "3000:3100"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    entrypoint: ["/bin/sh", "-c", "/etc/grafana/provisioning/entrypoint.sh"]
    networks:
      - mynetwork
    depends_on:
      - db

volumes:
  postgres_data:
  grafana_data:

networks:
  mynetwork:
