app = "covid-db"
primary_region = "fra"

[build]
# Pas besoin de builder une image, on utilise une image publique officielle

[env]
  POSTGRES_PASSWORD = "{{POSTGRES_PASSWORD}}"
  POSTGRES_USER = "{{POSTGRES_USER}}"
  POSTGRES_DB = "{{POSTGRES_DB}}"

[mounts]
  source = "pgdata"
  destination = "/var/lib/postgresql/data"

[[services]]
  internal_port = 5432
  protocol = "tcp"

  [[services.ports]]
    port = 5432
    handlers = ["tls", "tcp"]
