name: Integration Test Workflow

on: [push, pull_request]

jobs:
  # le premier job est un build. On construit notre image Docker pour tester que le Dockerfile fonctionne
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        # On construit l’image Docker en taguant :test, pour indiquer que c’est une image pour les tests CI
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/covid-mspr:test -f Dockerfile .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/covid-mspr:test

  # Ici, après avoir construit notre image, on lance toute l'infra Docker et les tests dans ce second job.
  start-services:
    name: Run Docker Infrastructure and Tests
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2

      # On ne pousse pas nos variables d'environnement dans le repo. On les stocke donc dans les secrets de GitHub.
      - name: Create .env file from secrets
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        working-directory: ${{ github.workspace }}
      # Une fois le fichier .env créé avec les variables qui sont stockées dans les secrets de Github, 
      # on lance les services Docker. On utilise docker compose pour ça.
      - name: Start Docker Compose services
        run: docker compose up -d
        working-directory: ${{ github.workspace }}


      - name: Wait for PostgreSQL to be ready
        run: |
          echo "⏳ Waiting for PostgreSQL..."
          for i in {1..10}; do
            docker exec postgres_db pg_isready -U postgres && exit 0
            sleep 3
          done
          echo "PostgreSQL not ready" && exit 1
      
      - name: Create database if not exists
        run: |
          echo "📦 Creating database if not exists..."
          docker exec postgres_db psql -U "${{ secrets.POSTGRES_USER }}" -d postgres -c \
          "DO \$\$ BEGIN IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${{ secrets.DB_NAME }}') THEN CREATE DATABASE \"${{ secrets.DB_NAME }}\"; END IF; END \$\$;"

      - name: Initialize database tables
        run: docker exec covid_mspr python /app/mspr1/covid_mspr1.py

      - name: Wait for FastAPI to be ready
        run: |
          echo "⏳ Waiting for FastAPI (localhost:8000)..."
          for i in {1..10}; do
            curl -s http://localhost:8000/docs > /dev/null && exit 0
            sleep 3
          done
          echo "FastAPI not ready" && exit 1

      - name: Show FastAPI logs if tests fail
        if: failure()
        run: docker logs covid_mspr

      # Un linter qui va nous aider à respecter les conventions de codage mais qui ne va pas bloquer le workflow
      # si on a des erreurs. On améliorera ça tout petit à petit.
      - name: Run flake8 linter (non bloquant)
        run: |
          docker exec covid_mspr pip install flake8
          docker exec covid_mspr flake8 . || true

      - name: Run tests with coverage
        # important : on lance les tests dans le conteneur backend où l'app est configurée
        run: docker exec covid_mspr pytest --cov=ws --cov-report=term-missing

      - name: Discord Notification
        uses: emvakar/discord-notification-action@v2
        with:
          title: "Test Workflow"
          status: "success"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  # Ce job lié à des notifcation de sécurité via des webhook Discord.
  # Il génére un rapport de sécurité avec Trivy, un scanner de vulnérabilités pour les images Docker.
  # et envoie le rapport sur un salon Discord.
  # Ensuite, on déclenche une notifcation pour informer l'équipe d'une nouvelle PR et de son état.
  notification-integration:
    name: Security Report
    runs-on: ubuntu-latest
    needs: [start-services]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image To Scan
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/covid-mspr:test

      - name: Run Trivy security scan and save report
        run: |
          docker run --rm -v ${{ github.workspace }}:/app aquasec/trivy image --severity HIGH,CRITICAL --exit-code 1 --format table --output trivy-report.txt ${{ secrets.DOCKER_USERNAME }}/covid-mspr:test

      - name: Send Trivy report to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
          -F "payload_json={\"content\":\"Rapport de sécurité Trivy\"}" \
          -F "file=@trivy-report.txt" \
          ${{ secrets.DISCORD_SECURITY_WEBHOOK }}

      - name: Discord Notification
        uses: emvakar/discord-notification-action@v2
        with:
          title: "Pull request déclenchée par ${{ github.actor }} sur `${{ github.ref_name }}`"
          status: "success"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}