name: Integration Test Workflow

on: [push, pull_request]

jobs:
  # le premier job est un build. On construit notre image Docker pour tester que le Dockerfile fonctionne
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        # On construit l’image Docker en taguant :test, pour indiquer que c’est une image pour les tests CI
        run: docker build -t covid-mspr:test -f Dockerfile .

  # Le second job lance les tests. Il dépend du job build (il s’exécute que si le build est OK)
  test:
    name: Run Tests and Linter
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      # On stocke les dépendances dans le cache pour éviter de les télécharger à chaque fois. Ça va accélerer
      #le workflow si on n'a pas changé les dépendances.
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt
      # Un linter qui va nous aider à respecter les conventions de codage mais qui ne va pas bloquer le workflow
      # si on a des erreurs. On améliorera ça tout petit à petit.
      - name: Run flake8 linter (non bloquant)
        run: |
          pip install flake8
          flake8 . || true

      - name: Run tests with coverage
        run: pytest --cov=ws --cov-report=term-missing

      - name: Discord Notification
        uses: emvakar/discord-notification-action@v2
        with:
          title: "Test Workflow"
          status: "success"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
